[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "ğŸ…° "

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[golang]
format = "[ğŸğŸ’¨ $version](bold cyan) "

[dart]
format = "[ğŸ”° $version](bold red) "

[lua]
format = "[ğŸŒ• $version](bold blue) "

[python]
symbol = "ğŸ‘¾ "
pyenv_version_name = true
python_binary = ["/Users/kiwamizamurai/.pyenv/shims/python"]

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
